version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis_db
      # SỬA LỖI TIMEZONE: Buộc database chạy theo giờ Việt Nam
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/gis_db?schema=public"

volumes:
  postgres_data:
