# Cổng 80 - Ép tất cả khách truy cập chuyển sang HTTPS
server {
    listen 80;
    server_name congvienxanhhcm.me;
    return 301 https://$host$request_uri;
}

# Cổng 443 - Mặt tiền bảo mật chính thức
server {
    listen 443 ssl;
    server_name congvienxanhhcm.me;

    # Đường dẫn trỏ tới file chứng chỉ TLS mày đã cài trên máy ảo
    ssl_certificate /etc/letsencrypt/live/congvienxanhhcm.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/congvienxanhhcm.me/privkey.pem;

    location / {
        proxy_pass http://qlycv_frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://qlycv_backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}