# Generated by Django 6.0.2 on 2026-03-01 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CongVien",
            fields=[
                ("ma_cong_vien", models.AutoField(primary_key=True, serialize=False)),
                ("ten_cong_vien", models.CharField(max_length=200)),
                (
                    "ma_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("dia_chi", models.TextField(blank=True, null=True)),
                (
                    "dien_tich_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "dien_tich_cay_xanh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "dien_tich_mat_nuoc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "toa_do_trung_tam",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("ranh_gioi", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "vi_tri_cong_vao",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "don_vi_quan_ly",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gio_mo_cua", models.TimeField(blank=True, null=True)),
                ("gio_dong_cua", models.TimeField(blank=True, null=True)),
                ("mo_cua_24_7", models.BooleanField(default=False)),
                ("mien_phi_vao_cua", models.BooleanField(default=True)),
                (
                    "gia_ve",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("nam_thanh_lap", models.IntegerField(blank=True, null=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("lich_su", models.TextField(blank=True, null=True)),
                (
                    "diem_trung_binh",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("so_luot_danh_gia", models.IntegerField(default=0)),
                (
                    "anh_dai_dien",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("da_xac_minh", models.BooleanField(default=False)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cong_vien",
                "ordering": ["-ngay_cap_nhat"],
            },
        ),
        migrations.CreateModel(
            name="DanhMucSuCo",
            fields=[
                ("ma_danh_muc", models.AutoField(primary_key=True, serialize=False)),
                ("ten_danh_muc", models.CharField(max_length=100, unique=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "danh_muc_su_co",
                "ordering": ["ten_danh_muc"],
            },
        ),
        migrations.CreateModel(
            name="LoaiCay",
            fields=[
                ("ma_loai_cay", models.AutoField(primary_key=True, serialize=False)),
                ("ten_loai", models.CharField(max_length=100, unique=True)),
                (
                    "ten_khoa_hoc",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "loai_cay",
                "ordering": ["ten_loai"],
            },
        ),
        migrations.CreateModel(
            name="LoaiCongVien",
            fields=[
                ("ma_loai", models.AutoField(primary_key=True, serialize=False)),
                ("ten_loai", models.CharField(max_length=100, unique=True)),
                ("ma_code", models.CharField(max_length=30, unique=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("icon_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mau_sac",
                    models.CharField(
                        blank=True,
                        help_text="Mã màu HEX (#RRGGBB)",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "loai_cong_vien",
                "ordering": ["ten_loai"],
            },
        ),
        migrations.CreateModel(
            name="LoaiKiemTra",
            fields=[
                (
                    "ma_loai_kiem_tra",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ten_loai", models.CharField(max_length=100, unique=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "loai_kiem_tra",
                "ordering": ["ten_loai"],
            },
        ),
        migrations.CreateModel(
            name="LoaiTienIch",
            fields=[
                (
                    "ma_loai_tien_ich",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ten_loai", models.CharField(max_length=100, unique=True)),
                ("ma_code", models.CharField(max_length=50, unique=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("icon_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "loai_tien_ich",
                "ordering": ["ten_loai"],
            },
        ),
        migrations.CreateModel(
            name="NhomQuyen",
            fields=[
                ("ma_nhom_quyen", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ten_nhom",
                    models.CharField(
                        choices=[
                            ("QUAN_TRI", "Quản trị viên"),

                            ("CONG_DONG", "Người dùng cộng đồng"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "nhom_quyen",
                "ordering": ["ma_nhom_quyen"],
            },
        ),
        migrations.CreateModel(
            name="PhuongXa",
            fields=[
                ("ma_phuong_xa", models.AutoField(primary_key=True, serialize=False)),
                ("ten_phuong_xa", models.CharField(max_length=100)),
                ("ma_code", models.CharField(max_length=20, unique=True)),
                (
                    "loai",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phuong", "Phường"),
                            ("xa", "Xã"),
                            ("thi_tran", "Thị trấn"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dien_tich_km2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("hinh_hoc", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "db_table": "phuong_xa",
                "ordering": ["ma_quan_huyen", "ten_phuong_xa"],
            },
        ),
        migrations.CreateModel(
            name="QuanHuyen",
            fields=[
                ("ma_quan_huyen", models.AutoField(primary_key=True, serialize=False)),
                ("ten_quan_huyen", models.CharField(max_length=100, unique=True)),
                ("ma_code", models.CharField(max_length=20, unique=True)),
                (
                    "loai",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quan", "Quận"),
                            ("huyen", "Huyện"),
                            ("tpthuduc", "TP Thủ Đức"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dien_tich_km2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("dan_so", models.IntegerField(blank=True, null=True)),
                ("hinh_hoc", models.JSONField(blank=True, default=dict, null=True)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "quan_huyen",
                "ordering": ["ten_quan_huyen"],
            },
        ),
        migrations.CreateModel(
            name="TrangThaiCongVien",
            fields=[
                ("ma_trang_thai", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ten_trang_thai",
                    models.CharField(
                        choices=[
                            ("quy_hoach", "Quy hoạch"),
                            ("dang_xay_dung", "Đang xây dựng"),
                            ("hoat_dong", "Hoạt động"),
                            ("cai_tao", "Cải tạo"),
                            ("tam_dong", "Tạm đóng"),
                            ("ngung_hoat_dong", "Ngưng hoạt động"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("ma_code", models.CharField(max_length=30, unique=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("mau_sac", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "trang_thai_cong_vien",
                "ordering": ["ma_trang_thai"],
            },
        ),
        migrations.CreateModel(
            name="HinhAnhCongVien",
            fields=[
                ("ma_hinh_anh", models.AutoField(primary_key=True, serialize=False)),
                ("url_anh", models.CharField(max_length=500)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("la_anh_chinh", models.BooleanField(default=False)),
                ("ngay_chup", models.DateField(blank=True, null=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hinh_anh",
                        to="parks.congvien",
                    ),
                ),
            ],
            options={
                "db_table": "hinh_anh_cong_vien",
                "ordering": ["ma_cong_vien", "-la_anh_chinh"],
            },
        ),
        migrations.AddField(
            model_name="congvien",
            name="ma_loai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cong_vien",
                to="parks.loaicongvien",
            ),
        ),
        migrations.CreateModel(
            name="NguoiDung",
            fields=[
                ("ma_nguoi_dung", models.AutoField(primary_key=True, serialize=False)),
                ("ten_dang_nhap", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mat_khau_hash", models.CharField(max_length=255)),
                ("ho_ten", models.CharField(blank=True, max_length=150, null=True)),
                ("dang_hoat_dong", models.BooleanField(default=True)),
                ("da_xac_thuc_email", models.BooleanField(default=False)),
                ("so_lan_dang_nhap", models.IntegerField(default=0)),
                (
                    "token",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("lan_dang_nhap_cuoi", models.DateTimeField(blank=True, null=True)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "ma_nhom_quyen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nguoi_dung",
                        to="parks.nhomquyen",
                    ),
                ),
            ],
            options={
                "db_table": "nguoi_dung",
                "ordering": ["-ngay_cap_nhat"],
            },
        ),
        migrations.AddField(
            model_name="congvien",
            name="ma_phuong_xa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cong_vien",
                to="parks.phuongxa",
            ),
        ),
        migrations.AddField(
            model_name="phuongxa",
            name="ma_quan_huyen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phuong_xa",
                to="parks.quanhuyen",
            ),
        ),
        migrations.AddField(
            model_name="congvien",
            name="ma_quan_huyen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cong_vien",
                to="parks.quanhuyen",
            ),
        ),
        migrations.CreateModel(
            name="SuKienCongVien",
            fields=[
                ("ma_su_kien", models.AutoField(primary_key=True, serialize=False)),
                ("ten_su_kien", models.CharField(max_length=200)),
                (
                    "loai_su_kien",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("le_hoi", "Lễ hội"),
                            ("the_thao", "Thể thao"),
                            ("van_hoa", "Văn hóa"),
                            ("am_nhac", "Âm nhạc"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("thoi_gian_bat_dau", models.DateTimeField()),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                ("la_su_kien_lap_lai", models.BooleanField(default=False)),
                ("mien_phi", models.BooleanField(default=True)),
                ("suc_chua_toi_da", models.IntegerField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("sap_dien_ra", "Sắp diễn ra"),
                            ("dang_dien_ra", "Đang diễn ra"),
                            ("da_ket_thuc", "Đã kết thúc"),
                            ("huy_bo", "Hủy bỏ"),
                        ],
                        default="sap_dien_ra",
                        max_length=30,
                    ),
                ),
                ("da_duyet", models.BooleanField(default=False)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="su_kien",
                        to="parks.congvien",
                    ),
                ),
            ],
            options={
                "db_table": "su_kien_cong_vien",
                "ordering": ["-thoi_gian_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="ThongKetruyenCap",
            fields=[
                ("ma_thong_ke", models.AutoField(primary_key=True, serialize=False)),
                ("ngay", models.DateField(auto_now_add=True)),
                ("so_lan_truy_cap", models.IntegerField(default=0)),
                ("so_nguoi_truy_cap_doc_lap", models.IntegerField(default=0)),
                (
                    "trang_tim_kiem_nhat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "thong_ke_truy_cap",
                "ordering": ["-ngay"],
                "unique_together": {("ngay",)},
            },
        ),
        migrations.CreateModel(
            name="TienIchCongVien",
            fields=[
                ("ma_tien_ich", models.AutoField(primary_key=True, serialize=False)),
                (
                    "so_luong",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "tinh_trang",
                    models.CharField(
                        choices=[
                            ("tot", "Tốt"),
                            ("kha", "Khá"),
                            ("trung_binh", "Trung bình"),
                            ("kem", "Kém"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("vi_tri", models.JSONField(blank=True, default=list, null=True)),
                ("dang_su_dung", models.BooleanField(default=True)),
                ("ngay_kiem_tra", models.DateField(blank=True, null=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tien_ich",
                        to="parks.congvien",
                    ),
                ),
                (
                    "ma_loai_tien_ich",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tien_ich_cong_vien",
                        to="parks.loaitienich",
                    ),
                ),
            ],
            options={
                "db_table": "tien_ich_cong_vien",
                "ordering": ["ma_cong_vien"],
            },
        ),
        migrations.AddField(
            model_name="congvien",
            name="ma_trang_thai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cong_vien",
                to="parks.trangthaicongvien",
            ),
        ),
        migrations.CreateModel(
            name="CayXanh",
            fields=[
                ("ma_cay", models.AutoField(primary_key=True, serialize=False)),
                ("ma_so_cay", models.CharField(blank=True, max_length=50, null=True)),
                ("vi_tri", models.JSONField(default=list)),
                (
                    "chieu_cao_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "duong_kinh_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "ban_kinh_tan_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tinh_trang",
                    models.CharField(
                        choices=[
                            ("tot", "Tốt"),
                            ("kha", "Khá"),
                            ("trung_binh", "Trung bình"),
                            ("kem", "Kém"),
                            ("chet", "Chết"),
                        ],
                        default="tot",
                        max_length=50,
                    ),
                ),
                ("ngay_cat_tia_cuoi", models.DateField(blank=True, null=True)),
                ("ngay_trong", models.DateField(blank=True, null=True)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cay_xanh",
                        to="parks.congvien",
                    ),
                ),
                (
                    "ma_loai_cay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parks.loaicay",
                    ),
                ),
            ],
            options={
                "db_table": "cay_xanh",
                "ordering": ["ma_cong_vien"],
                "indexes": [
                    models.Index(
                        fields=["ma_cong_vien"], name="cay_xanh_ma_cong_0dbc6e_idx"
                    ),
                    models.Index(
                        fields=["tinh_trang"], name="cay_xanh_tinh_tr_426161_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KiemTraCongVien",
            fields=[
                ("ma_kiem_tra", models.AutoField(primary_key=True, serialize=False)),
                ("ngay_kiem_tra", models.DateField()),
                (
                    "ket_qua",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dat", "Đạt"),
                            ("khong_dat", "Không đạt"),
                            ("can_chu_y", "Cần chú ý"),
                            ("nguy_hiem", "Nguy hiểm"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "diem_tong",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "diem_ve_sinh",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "diem_an_toan",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "diem_tien_ich",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("van_de_phat_hien", models.TextField(blank=True, null=True)),
                ("khuyen_nghi", models.TextField(blank=True, null=True)),
                ("han_xu_ly", models.DateField(blank=True, null=True)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiem_tra",
                        to="parks.congvien",
                    ),
                ),
                (
                    "ma_loai_kiem_tra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parks.loaikiemtra",
                    ),
                ),
                (
                    "ma_nguoi_kiem_tra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parks.nguoidung",
                    ),
                ),
            ],
            options={
                "db_table": "kiem_tra_cong_vien",
                "ordering": ["-ngay_kiem_tra"],
                "indexes": [
                    models.Index(
                        fields=["ma_cong_vien", "ngay_kiem_tra"],
                        name="kiem_tra_co_ma_cong_a8d451_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DanhGiaCongVien",
            fields=[
                ("ma_danh_gia", models.AutoField(primary_key=True, serialize=False)),
                (
                    "diem_tong_quat",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "diem_ve_sinh",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "diem_tien_ich",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "diem_an_toan",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "diem_tieu_can_thi",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("noi_dung", models.TextField(blank=True, null=True)),
                ("da_duyet", models.BooleanField(default=False)),
                ("vi_tri", models.JSONField(blank=True, default=list, null=True)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_gia",
                        to="parks.congvien",
                    ),
                ),
                (
                    "ma_nguoi_dung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="danh_gia",
                        to="parks.nguoidung",
                    ),
                ),
            ],
            options={
                "db_table": "danh_gia_cong_vien",
                "ordering": ["-ngay_tao"],
                "indexes": [
                    models.Index(
                        fields=["ma_cong_vien", "da_duyet"],
                        name="danh_gia_co_ma_cong_c5009a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BaoCaoSuCo",
            fields=[
                ("ma_bao_cao", models.AutoField(primary_key=True, serialize=False)),
                ("tieu_de", models.CharField(max_length=200)),
                ("noi_dung_mo_ta", models.TextField()),
                (
                    "url_hinh_anh",
                    models.JSONField(
                        blank=True, default=list, help_text="Mảng JSON URL ảnh"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("cho_xu_ly", "Chờ xử lý"),
                            ("dang_xu_ly", "Đang xử lý"),
                            ("da_xu_ly", "Đã xử lý"),
                        ],
                        default="cho_xu_ly",
                        max_length=30,
                    ),
                ),
                (
                    "muc_do_uu_tien",
                    models.CharField(
                        choices=[
                            ("thap", "Thấp"),
                            ("trung_binh", "Trung bình"),
                            ("cao", "Cao"),
                            ("khan_cap", "Khẩn cấp"),
                        ],
                        default="trung_binh",
                        max_length=20,
                    ),
                ),
                ("vi_tri", models.JSONField(blank=True, default=list, null=True)),
                ("so_nguoi_xac_nhan", models.IntegerField(default=0)),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "ma_cong_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bao_cao_su_co",
                        to="parks.congvien",
                    ),
                ),
                (
                    "ma_danh_muc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parks.danhmucsuco",
                    ),
                ),
                (
                    "ma_nguoi_bao_cao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bao_cao_da_tao",
                        to="parks.nguoidung",
                    ),
                ),
                (
                    "ma_nguoi_phu_trach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bao_cao_phu_trach",
                        to="parks.nguoidung",
                    ),
                ),
            ],
            options={
                "db_table": "bao_cao_su_co",
                "ordering": ["-ngay_tao"],
                "indexes": [
                    models.Index(
                        fields=["ma_cong_vien", "trang_thai"],
                        name="bao_cao_su__ma_cong_02cdc2_idx",
                    ),
                    models.Index(
                        fields=["muc_do_uu_tien"], name="bao_cao_su__muc_do__b2c423_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NhatKyThayDoi",
            fields=[
                ("ma_nhat_ky", models.AutoField(primary_key=True, serialize=False)),
                (
                    "loai_thay_doi",
                    models.CharField(
                        choices=[
                            ("tao_moi", "Tạo mới"),
                            ("cap_nhat", "Cập nhật"),
                            ("xoa_mem", "Xóa mềm"),
                            ("phuc_hoi", "Phục hồi"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bang_du_lieu", models.CharField(max_length=100)),
                ("id_ban_ghi", models.IntegerField()),
                ("du_lieu_truoc", models.JSONField(blank=True, null=True)),
                ("du_lieu_sau", models.JSONField(blank=True, null=True)),
                ("mo_ta", models.CharField(blank=True, max_length=500, null=True)),
                ("ngay_thay_doi", models.DateTimeField(auto_now_add=True)),
                (
                    "ma_nguoi_dung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parks.nguoidung",
                    ),
                ),
            ],
            options={
                "db_table": "nhat_ky_thay_doi",
                "ordering": ["-ngay_thay_doi"],
                "indexes": [
                    models.Index(
                        fields=["bang_du_lieu", "id_ban_ghi"],
                        name="nhat_ky_tha_bang_du_ffcbe2_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="nguoidung",
            index=models.Index(
                fields=["ten_dang_nhap"], name="nguoi_dung_ten_dan_1f8318_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nguoidung",
            index=models.Index(fields=["email"], name="nguoi_dung_email_d26f14_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="phuongxa",
            unique_together={("ma_quan_huyen", "ten_phuong_xa")},
        ),
        migrations.AddIndex(
            model_name="sukiencongvien",
            index=models.Index(
                fields=["ma_cong_vien", "trang_thai"],
                name="su_kien_con_ma_cong_1aa832_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="congvien",
            index=models.Index(fields=["ma_loai"], name="cong_vien_ma_loai_49d7d1_idx"),
        ),
        migrations.AddIndex(
            model_name="congvien",
            index=models.Index(
                fields=["ma_trang_thai"], name="cong_vien_ma_tran_6cf7b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="congvien",
            index=models.Index(
                fields=["ma_quan_huyen"], name="cong_vien_ma_quan_2c75ba_idx"
            ),
        ),
    ]
