# Generated by Django 4.1.13 on 2026-03-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0006_add_permission_roles_manager_assignment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="baocaosuco",
            new_name="bao_cao_su__is_arch_c13166_idx",
            old_name="bao_cao_su__is_arch_b72d8f_idx",
        ),
    ]
