pipeline {
    agent any
    environment {
        APP_NAME = 'ecommerce-api'
    }
    stages {
        stage('Build & Push Docker') {
            steps {
                echo 'Dang dong goi va day image len kho...'
                // Code build image nam o day
            }
        }
        stage('Cho Phe Duyet (Manual Approval)') {
            steps {
                // He thong se dung hinh o day va cho con nguoi bam nut
                input message: 'Image da san sang. Co dong y trien khai len K3s khong sếp?', ok: 'Deploy Ngay!'
            }
        }
        stage('Deploy to K3s (Controlled)') {
            steps {
                echo 'Da duoc phep! Tien hanh cap nhat len K3s...'
            }
        }
    }
}