import re

def fix_with_clean(corrupt_path):
    with open(corrupt_path, 'r', encoding='utf-8') as f:
        corrupt = f.read()
        
    corrupt = corrupt.replace('Ä‚â€Ă¢â‚¬ËœÄ‚¡Ă‚»Ă¢â€Â¢ng', 'động')
    corrupt = corrupt.replace('cÄ‚¡Ă‚ºĂ‚Â­p nhÄ‚¡Ă‚ºĂ‚­t', 'cập nhật')
    corrupt = corrupt.replace('cáº­p nháº­t', 'cập nhật')
    corrupt = corrupt.replace('Ä‘á»™', 'độ')
    corrupt = corrupt.replace('Ä‘iá»\x81n', 'điền')
    corrupt = corrupt.replace('yĂªu cáº§u', 'yêu cầu')
    corrupt = corrupt.replace('Ä‘Ă£ chá»\x8dn', 'đã chọn')
    corrupt = corrupt.replace('CĂ´ng viĂªn Tao ÄĂ n', 'Công viên Tao Đàn')
    corrupt = corrupt.replace('Äáº¡t', 'Đạt')
    corrupt = corrupt.replace('MĂ´ táº£', 'Mô tả')
    corrupt = corrupt.replace('chi tiáº¿t', 'chi tiết')
    corrupt = corrupt.replace('Giá»›i thiá»‡u', 'Giới thiệu')
    corrupt = corrupt.replace('Ä‘iá»\x81u kiá»‡n', 'điều kiện')
    corrupt = corrupt.replace('giá»\x9d mở cá»\xada', 'giờ mở cửa')
    corrupt = corrupt.replace('chi phĂ­', 'chi phí')
    corrupt = corrupt.replace('sá»\xad dá»¥ng', 'sử dụng')
    corrupt = corrupt.replace('tĂªn trường backend yĂªu cáº§u', 'tên trường backend yêu cầu')
    corrupt = corrupt.replace('Xá»\xad lĂ½ xóa ảnh công viên Ä‘Ă£ chá»\x8dn', 'Xử lý xóa ảnh công viên đã chọn')
    corrupt = corrupt.replace('Xá»\xad lĂ½ xóa ảnh tiện ích Ä‘Ă£ chá»\x8dn', 'Xử lý xóa ảnh tiện ích đã chọn')
    corrupt = corrupt.replace('cÄ‚¡Ă‚ºĂ‚Â­p', 'cập')
    corrupt = corrupt.replace('nhÄ‚¡Ă‚ºĂ‚­t', 'nhật')
    corrupt = corrupt.replace('Ä‚â€Ă¢â‚¬ËœÄ‚¡Ă‚»Ă¢â€Â¢', 'độ')
    corrupt = corrupt.replace('LÄ‚¡Ă‚»Ă¢â‚¬â€i', 'Lỗi')
    corrupt = corrupt.replace('Ä‚¡Ă‚ºĂ‚Â£nh', 'ảnh')
    corrupt = corrupt.replace('Ä‚¡Ă‚»Ă¢â‚¬Âºi', 'ới')
    corrupt = corrupt.replace('Ä‚¡Ă‚ºĂ‚£nh', 'ảnh')
    corrupt = corrupt.replace('Ä‚â€Ă¢â‚¬ËœÄ‚¡Ă‚»Ă¢â€Â¢ng', 'động')
    corrupt = corrupt.replace('lĂ„â€Ă‚Â\xa0', 'là ')
    corrupt = corrupt.replace('thiÄ‚¡Ă‚ºĂ‚¿u', 'thiếu')
    corrupt = corrupt.replace('vĂ„â€Ă‚Â\xa0', 'và ')
    corrupt = corrupt.replace('QuÄ‚¡Ă‚ºĂ‚Â­n', 'Quận')
    corrupt = corrupt.replace('HuyÄ‚¡Ă‚»Ă¢â‚¬Â¡n', 'Huyện')
    corrupt = corrupt.replace('cÄ‚â€¦Ă‚Â©', 'cũ')
    corrupt = corrupt.replace('HĂ„â€Ă‚Â¬nh', 'Hình')
    corrupt = corrupt.replace('XĂ„â€Ă‚³a', 'Xóa')
    corrupt = corrupt.replace('tÄ‚â€ Ă‚Â°Ä‚¡Ă‚»Ă‚Âng', 'tường')
    corrupt = corrupt.replace('Ä‚â€Ă‚ÂĂ„â€Ă‚Â£', 'Đã')
    corrupt = corrupt.replace('XÄ‚¡Ă‚»Ă‚Â­', 'Xử')
    corrupt = corrupt.replace('giÄ‚¡Ă‚»Ă¢â‚¬Âºi', 'giới')
    corrupt = corrupt.replace('Ä‚â€Ă‚ÂĂ„â€Ă‚£', 'Đã')
    corrupt = corrupt.replace('sÄ‚¡Ă‚»Ă‚Â­a', 'sửa')
    corrupt = corrupt.replace('CĂ„â€Ă‚Â´ng', 'Công')
    corrupt = corrupt.replace('Ä‚â€Ă‚ÂĂ„â€Ă‚Â\xa0n', 'Đàn')
    corrupt = corrupt.replace('tÄ‚¡Ă‚ºĂ‚Â£', 'tả')
    corrupt = corrupt.replace('tiÄ‚¡Ă‚ºĂ‚¿t', 'tiết')
    corrupt = corrupt.replace('Ä‚â€Ă‚ÂoÄ‚¡Ă‚ºĂ‚Â¡n', 'Đoạn')
    corrupt = corrupt.replace('dĂ„â€Ă‚¹ng', 'dùng')
    corrupt = corrupt.replace('lĂ„â€Ă‚Â\xa0m', 'làm')
    corrupt = corrupt.replace('nÄ‚¡Ă‚»Ă¢â€Â¢i', 'nội')
    corrupt = corrupt.replace('chĂ„â€Ă‚\xadnh', 'chính')
    corrupt = corrupt.replace('bĂ„â€Ă‚Â\xa0i', 'bài')
    corrupt = corrupt.replace('viÄ‚¡Ă‚ºĂ‚Â¿t', 'viết')
    corrupt = corrupt.replace('lÄ‚¡Ă‚»Ă¢â‚¬Â¹ch', 'lịch')
    corrupt = corrupt.replace('sÄ‚¡Ă‚»Ă‚Â­', 'sử')
    corrupt = corrupt.replace('viÄ‚¡Ă‚ºĂ‚¿t', 'viết')
    corrupt = corrupt.replace('Ä‚¡Ă‚ºĂ‚\xadn', 'ận')
    corrupt = corrupt.replace('ThĂ„â€Ă‚¡i', 'Thái')
    corrupt = corrupt.replace('LoÄ‚¡Ă‚ºĂ‚¡i', 'Loại')
    corrupt = corrupt.replace('CĂ„â€Ă‚´ng', 'Công')
    corrupt = corrupt.replace('ViĂ„â€Ă‚ªn', 'Viên')
    corrupt = corrupt.replace('TÄ‚¡Ă‚»Ă‚Â\x8da', 'Tọa')
    corrupt = corrupt.replace('bÄ‚¡Ă‚ºĂ‚¡n', 'bạn')
    corrupt = corrupt.replace('Ä‚¡Ă‚ºĂ‚¢nh', 'Ảnh')
    corrupt = corrupt.replace('TiÄ‚¡Ă‚»Ă¢â‚¬Â¡n', 'Tiện')
    corrupt = corrupt.replace('Ă„â€Ă‚Â\x8dch', 'ích')
    corrupt = corrupt.replace('QuÄ‚¡Ă‚ºĂ‚Â£n', 'Quản')
    corrupt = corrupt.replace('CĂ„â€Ă‚¢y', 'Cây')
    corrupt = corrupt.replace('ChiÄ‚¡Ă‚»Ă‚Â\x81u', 'Chiều')
    corrupt = corrupt.replace('lÄ‚â€ Ă‚Â°u', 'lưu')
    
    with open(corrupt_path, 'w', encoding='utf-8') as f:
        f.write(corrupt)

fix_with_clean('frontend/src/pages/EditParkPage.jsx')
fix_with_clean('frontend/src/pages/CreateParkPage.jsx')
print("Direct replacement complete.")