# Generated by Django 4.1.13 on 2026-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0002_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienichcongvien",
            name="hinh_anh",
            field=models.JSONField(
                blank=True, default=list, help_text="Danh sách URL ảnh minh họa"
            ),
        ),
    ]
