# Generated by Django 4.1.13 on 2026-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0003_tienichcongvien_hinh_anh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baocaosuco",
            name="url_hinh_anh",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="loaicongvien",
            name="mau_sac",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="tienichcongvien",
            name="hinh_anh",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
