# Generated by Django 4.1.13 on 2026-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parks",
            "0007_rename_bao_cao_su__is_arch_b72d8f_idx_bao_cao_su__is_arch_c13166_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="baocaosuco",
            name="dia_chi",
            field=models.TextField(
                blank=True, help_text="Địa chỉ dựa trên công viên gần nhất", null=True
            ),
        ),
    ]
